[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "argrelay"
dynamic = ["version"]
authors = [
    { name = "uvsmtid", email = "uvsmtid@gmail.com" },
]
description = "A data server to CLI tools with attribute search & Tab-completion in Bash shell"
readme = "readme.md"
keywords = ["argparse", "argcomplete", "bash", "complete"]
license = { file = "LICENSE" }
# FS_84_11_73_28: supported python versions:
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Framework :: Flask",
    "Intended Audience :: Information Technology",
    "Topic :: Terminals",
    "Topic :: System :: Shells",
    "Topic :: Scientific/Engineering :: Human Machine Interfaces",
    "Topic :: Text Processing :: Indexing",
    "Topic :: Internet :: WWW/HTTP :: Indexing/Search",
    "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: POSIX :: Linux",
]
dependencies = [
    "Flask",
    "Werkzeug",
    "PyYaml",
    "jsonschema",
    "flasgger",
    "marshmallow>=3.0.0,<5.0.0",
    "marshmallow-oneofschema",
    "apispec",
    "pymongo",
    "GitPython",
    "mongomock",
    "requests",
    "cachetools",
    "mcp>=1.0",
    # NOTE: URL spec to use from remote git repo directly:
    # "protoprimer @ git+https://github.com/uvsmtid/protoprimer.git@branch_name#subdirectory=src/protoprimer&egg=protoprimer",
    "protoprimer==0.13.0.dev3",
]

[project.urls]
"Homepage" = "https://github.com/argrelay/argrelay"
"Bug Tracker" = "https://github.com/argrelay/argrelay/issues"

[project.optional-dependencies]
tests = [
    "pytest",
    "tox",
    "responses",
    # Use `mongomock` as a replacement for Mongo DB in simple prod cases:
    "mongomock",
    "pandas",
    "icecream",
    "jsonpath-ng",
    "import-linter",
    "pyfakefs",
    "freezegun",
]

[tool.setuptools.dynamic]
version = { attr = "argrelay._version.__version__" }

[tool.setuptools]
include-package-data = true

# See the sample layout:
# https://docs.python.org/3.8/distutils/setupscript.html#installing-package-data
# List all packages/sub-packages:
[tool.setuptools.packages.find]
where = ["src"]

# See:
# https://docs.python.org/3.8/distutils/setupscript.html#installing-package-data
#     The paths are interpreted as relative to the directory containing the package
#     (information from the `package_dir` mapping is used if appropriate);
#     that is, the files are expected to be part of the package in the source directories.
[tool.setuptools.package-data]
"argrelay" = [
    # Other resource files:
    "custom_integ_res/argrelay_common_lib.bash",
    "custom_integ_res/shell_env.bash",

    "custom_integ_res/check_env.bash",
    "custom_integ_res/dev_shell.bash",
    "custom_integ_res/init_shell_env.bash",
    "custom_integ_res/shell_env.zsh",
    "custom_integ_res/dev_shell.zsh",
    "custom_integ_res/init_shell_env.zsh",
    "custom_integ_res/upgrade_env_packages.bash",
    # Files in `script_plugin.d`:
    "custom_integ_res/script_plugin.d/check_env_plugin.all_argrelay_plugins.bash",
    "custom_integ_res/script_plugin.d/check_env_plugin.bash_version.bash",
    "custom_integ_res/script_plugin.d/check_env_plugin.git_version.bash",
]
"argrelay_app_bootstrap" = [
    # Config files:
    "sample_conf/argrelay_client.json",
    "sample_conf/argrelay_server.yaml",
    "sample_conf/argrelay_plugin.yaml",
    "sample_conf/check_env_plugin.conf.bash",
    "sample_conf/check_env_plugin.conf.yaml",
]
"argrelay_app_server" = [
    # GUI client:
    "relay_server/gui_static/argrelay_client.js",
    "relay_server/gui_static/argrelay_favicon_16.ico",
    "relay_server/gui_static/argrelay_style.css",
    "relay_server/gui_static/external_link.svg",
    "relay_server/gui_templates/argrelay_main.html",
]

[tool.pytest.ini_options]
# Add `src` and `tests` as source roots (prod and test respectively):
pythonpath = [
    "src",
    "tests",
]
norecursedirs = [
    "tmp",
]
