#!/usr/bin/env zsh
# `argrelay` integration file: https://github.com/argrelay/argrelay
# It is configured via `@/conf/shell_env.conf.bash`.

# This script is source-able by `~/.zshrc`:
#     source path/to/argrelay_dir/exe/shell_env.zsh

# The main purposes of this script:
# *   enable auto-completion for the commands configured via `argrelay_bind_command_basenames`
# *   add the commands to PATH

# Normally, this script is a symlink to orig artifact from `argrelay` distrib package.
# The path where this symlink (or copy) is located is supposed to contain:
# *   `@/exe/run_argrelay_client` artifact (generated by `@/exe/bootstrap_env.py`)
# *   `@/conf/shell_env.conf.bash` defining `argrelay_bind_command_basenames` env var
# The symlinks for all command names are created by `@/exe/bootstrap_env.py` and
# point to `@/exe/run_argrelay_client`.

# Note that enabling exit on error (like `set -e` below) will exit parent Zsh shell (as this one is sourced).
# Use these options with care as it prevents starting any shell in case of errors.

# Define with `s` in value to debug:
if [[ "${ARGRELAY_DEBUG-}" == *s* ]]
then
    set -x
    set -v
fi

if [[ -n "${argrelay_rc_old_opts+x}" ]] ; then exit 1 ; fi

# Save `set`-able options to restore them at the end of this source-able script:
# https://unix.stackexchange.com/a/383581/23886
# See `@/exe/bootstrap_env.py` regarding `history`:
argrelay_rc_old_opts="$( set +o | grep -v "[[:space:]]history$" )"
case "${-}" in
    *e*) argrelay_rc_old_opts="${argrelay_rc_old_opts}; set -e" ;;
      *) argrelay_rc_old_opts="${argrelay_rc_old_opts}; set +e" ;;
esac

# Debug: Print commands before execution:
#set -x
# Debug: Print commands after reading from a script:
#set -v
# Return non-zero exit code from commands within a pipeline:
set -o pipefail
# Exit on non-zero exit code from a command:
set -e
# Zsh uses `setopt ERR_RETURN` instead of Bash `set -E` to inherit trap on ERR by sub-shells:
setopt ERR_RETURN
# Error on undefined variables:
set -u

# TODO: This is a stop gap workaround (to allow FS_57_36_37_48 multiple clients coexistence):
#       Prefix all shared vars (e.g. `argrelay_dir`) set here with `argrelay_rc` and unset them on exit.
#       With multiple clients, sourcing the second `@/exe/shell_env.zsh` reset shared env vars used by the first.
#       See TODO_27_61_22_18: Long term solution is to make these vars local (not shared).
argrelay_rc_script_source="${(%):-%N}"
# It is expected that `@/exe/shell_env.zsh` is sourced from the project dir.
# The dir of this script:
argrelay_rc_script_dir="$( cd -- "$( dirname -- "${argrelay_rc_script_source}" )" &> /dev/null && pwd )"
# FS_29_54_67_86 dir_structure: `@/exe/` -> `@/`:
argrelay_rc_argrelay_dir="$( dirname "${argrelay_rc_script_dir}" )"

# Test files generated by `@/exe/bootstrap_env.py` script:
test -f "${argrelay_rc_argrelay_dir}/exe/run_argrelay_server" || return 1
test -f "${argrelay_rc_argrelay_dir}/exe/run_argrelay_client" || return 1
test -f "${argrelay_rc_argrelay_dir}/conf/shell_env.conf.bash" || return 1

# Load user config for env vars:
# *   argrelay_bind_command_basenames
source "${argrelay_rc_argrelay_dir}/conf/shell_env.conf.bash"

# shellcheck disable=SC2154
if [[ "${#argrelay_bind_command_basenames[@]}" -lt 1 ]]
then
    # At least one command should be listed in `argrelay_bind_command_basenames`:
    return 1
fi

# FS_57_36_37_48 multiple clients coexistence: this maps each symlink basename to its client path
# so that `Alt+Shift+Q` can use `argrelay_basename_to_client_path_map` to select correct client path:
typeset -A argrelay_basename_to_client_path_map

# Any (the first) command:
# Zsh arrays are 1-based:
export ARGRELAY_CLIENT_COMMAND="${argrelay_bind_command_basenames[1]}"

# Zsh completion function wrapper:
_argrelay_completion_wrapper() {
    local argrelay_command_basename="${words[1]}"
    local client_path="${argrelay_basename_to_client_path_map[$argrelay_command_basename]}"

    if [[ -n "$client_path" ]]
    then
        local -a choices
        # Pass COMP_* vars inline to avoid leaking them into the shell env (which would cause
        # subsequent Enter to be mistaken for a completion call instead of InvokeAction).
        choices=(${(f)"$(COMP_LINE="$BUFFER" COMP_POINT="$CURSOR" COMP_TYPE="9" COMP_KEY="88" $client_path)"})
        compadd -a choices
    fi
}

for argrelay_command_basename in "${argrelay_bind_command_basenames[@]}"
do
    # Enable auto-completion for `${argrelay_command_basename}` command:
    compdef _argrelay_completion_wrapper "${argrelay_command_basename}"

    argrelay_basename_to_client_path_map[$argrelay_command_basename]="${argrelay_rc_argrelay_dir}/exe/run_argrelay_client"
done

# Invoke completion programmatically:
function invoke_completion {
    # Run client in subshell to avoid leaking COMP_* vars into shell env (mirrors Bash's ( ) in shell_env.bash).
    (
        export COMP_LINE="${BUFFER}"
        export COMP_POINT="${CURSOR}"
        # CompType.DescribeArgs = ASCII '@':
        export COMP_TYPE="94"
        # NOTE: Not useful: for any key sequence, it is only set to the last key (no use case at the moment).
        export COMP_KEY="88"

        local argrelay_command_basename
        local command_components=( ${(z)BUFFER} )
        local command_name="${command_components[1]}"
        argrelay_command_basename="$( basename "${command_name}" )"
        if [[ -n "${argrelay_basename_to_client_path_map[$argrelay_command_basename]+x}" ]]
        then
            # FS_57_36_37_48 multiple clients coexistence:
            # The symlink basename is found, use correct client path:
            "${argrelay_basename_to_client_path_map[$argrelay_command_basename]}"
        else
            local basename_color="\e[41m"
            local reset_color="\e[0m"
            echo -e "WARN: unknown \`argrelay\` client path for command: ${basename_color}${argrelay_command_basename}${reset_color}" 1>&2
        fi

        # TODO: Does it depend on the height of the prompt line?
        # Ensure prompt does not overwrite the last output line when ZLE redraws:
        echo
    )

    zle redisplay

    # Save command into history:
    print -s "# ${BUFFER}"
}

# Bind Alt+Shift+Q to `invoke_completion` function.
zle -N invoke_completion
bindkey '\eQ' invoke_completion

# Add dir with `${argrelay_bind_command_basenames}` into PATH to make them available in Zsh as plain `basename`:
PATH="${argrelay_rc_argrelay_dir}/bin/:${PATH}"
export PATH

eval "${argrelay_rc_old_opts}"
unset argrelay_rc_old_opts

unset argrelay_rc_script_source
unset argrelay_rc_script_dir
unset argrelay_rc_argrelay_dir
