#!/usr/bin/env bash

# This script is only used to test Bash auto-completion.
# Bash config in `dev-init.bash` binds Bash auto-completion to the name of this script.

# Return first non-zero exit code from commands in a pipeline:
set -o pipefail
# Exit on non-zero exit code from a command:
set -e
# Error on undefined variables:
set -u
# Debug: Print commands after reading from a script:
# set -v
# Debug: Print commands before execution:
# set -x

red_color="\e[32m"
color_reset="\e[0m"
echo -e "${red_color}all args:${color_reset}" "${@}"
# Add name of this script (used to bind completion) as the first arg and pass through all given args:
python -m argrelay.relay_client "$0" "${@}"
